version: '1'
services:
  mongo-gui:
    container_name: "mongogui"
    build:
      context: .
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://mongodb.local:27017
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb.local
    ports:
      - "27017:27017"
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mongodb