version: '3'

services:
  mongo-gui:
    container_name: "mongo-gui"
    build:
      context: ./client
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400m
        reservations:
          cpus: '0.1'
          memory: 200m
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://mongodb.local:27017
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb.local
    ports:
      - "27017:27017"
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mongodb

networks:
  default:
    name: guinet
    external: true