POST http://localhost:3000/databases/580a07b8d5be18c823242213/collections/580a07b8d5be18c823242213-Reqre/documents/filter
Content-Type: application/json

{
 "_id": "8"
}
###
PATCH http://localhost:3000/databases/580a07b8d5be18c823242213/collections/580a07b8d5be18c823242213-Reqre/documents/filter
Content-Type: application/json

{
    "a": 7
}

###
DELETE http://localhost:3000/databases/abcd

###

GET http://localhost:3000/databases/580a07b8d5be18c823242213/collections/580a07b8d5be18c823242213-Reqre/documents/
Content-Type: application/json
###

POST http://localhost:3000/databases/quiz/collections
Content-Type: application/json

{
    "collectionName": "employees",
    "dbName": "quiz"
}

###

DELETE http://localhost:3000/databases/quiz/collections/result

###
http://localhost:4321/databases/ApplaudCloud/collections/Form/documents/